apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-service
spec:
  type: ClusterIP
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: agent-prometheus
  selector:
    k8s-app: {{ .Release.Name }}
    type: agent
    version: v1