apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: prometheus
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: lapi
    {{ if .Values.lapi.dashboard.enabled }}
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: dashboard
    {{ end }}
  selector:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1