apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lapi
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
      type: lapi
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        type: lapi
        version: v1
    spec:
      {{ if .Values.lapi.dashboard.enabled }}
      initContainers:
      - name: fetch-metabase-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'wget {{ .Values.lapi.dashboard.assetURL }} && unzip metabase_sqlite.zip -d /metabase-data/']
        volumeMounts:
        - name: shared-data
          mountPath: /metabase-data
      {{ end }}
      containers:
      - name: crowdsec-lapi
        image: "{{ .Values.image.repository | default "crowdsecurity/crowdsec" }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: AGENT_USERNAME
            valueFrom:
              secretKeyRef:
                name: agent-credentials
                key: username
          - name: AGENT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: agent-credentials
                key: password
        {{- with .Values.lapi.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.lapi.resources | nindent 10 }}
        ports:
          - name: lapi
            containerPort: 8080
            protocol: TCP
          - name: lapi-prometheus
            containerPort: 6060
            protocol: TCP
      {{ if .Values.lapi.dashboard.enabled }}
        volumeMounts:
          - name: crowdsec-db
            mountPath: /var/lib/crowdsec/data
      - name: dashboard
        image: "{{ .Values.lapi.dashboard.image.repository | default "metabase/metabase" }}:{{ .Values.lapi.dashboard.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.lapi.dashboard.image.pullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /metabase-data
        - name: crowdsec-db
          mountPath: /var/lib/crowdsec/data
        env:
          - name: MB_DB_FILE
            value: /metabase-data/metabase.db
      {{ end }}
      terminationGracePeriodSeconds: 30
      {{ if .Values.lapi.dashboard.enabled }}
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: crowdsec-db
        emptyDir: {}
      {{ end }}